server:
  port: 8080
logging:
  level:
    ROOT: INFO
    com.nl.cgi.bff: DEBUG
persistence:
  service:
    baseUrl: http://localhost:7001/
    dishesDetailsUrl: dishes-persistence-service/recipes-details
    ingredientsDetailsUrl: ingredients-persistence-service/ingredients-details
    foodRecipesDetailsUrl: food-persistence-service/food-recipes-details
    memorySizeInMb: 256
    readTimeOut: 120000
    writeTimeOut: 120000
    responseTimeOut: 120000
    connectionTimeOut: 1000
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



